const GET_GENRES = "GET_GENRES";
const GET_VIDEOGAMES = "GET_VIDEOGAMES";
const GET_VIDEOGAME = "GET_VIDEOGAME";
const GET_VIDEOGAMEBYNAME = "GET_VIDEOGAMEBYNAME";
const FILTER = "FILTER";
const ORDER = "ORDER";

export {
  GET_GENRES,
  GET_VIDEOGAMES,
  GET_VIDEOGAME,
  GET_VIDEOGAMEBYNAME,
  FILTER,
  ORDER,
};
